# TensorFlow type stubs to help Pylance
from typing import Any

# Simplified type stubs for TensorFlow
class keras:
    class layers:
        class Layer: ...
        class Dense: ...
        class Dropout: ...
        class GlobalAveragePooling2D: ...
        class BatchNormalization: ...
        class MultiHeadAttention: ...
        class LayerNormalization: ...
        class Add: ...
        class Input: ...
        
    class applications:
        class ResNet50: ...
        class EfficientNetB0: ...
        class MobileNetV2: ...
        class DenseNet121: ...
        class VGG16: ...
        
    class preprocessing:
        class image:
            class ImageDataGenerator: ...
            
    class callbacks:
        class EarlyStopping: ...
        class ReduceLROnPlateau: ...
        class ModelCheckpoint: ...
        
    class optimizers:
        class Adam: ...
        
    class models:
        class Model: ...
        
    class utils:
        def to_categorical(*args, **kwargs) -> Any: ...
        
    class Sequential: ...
    
def __version__() -> str: ...