import { useState, useEffect } from 'react';
import axios from 'axios';
import {
  HeartIcon,
  FireIcon,
  BeakerIcon,
  MoonIcon,
  LightBulbIcon,
  UsersIcon,
  SparklesIcon,
} from '@heroicons/react/24/outline';

interface LifestyleRecommendation {
  category: string;
  recommendations: Array<{
    title: string;
    description: string;
    priority: 'high' | 'medium' | 'low';
  }>;
}

interface LifestyleRecommendationsViewProps {
  reportId: string;
}

const LifestyleRecommendationsView = ({ reportId }: LifestyleRecommendationsViewProps) => {
  const [recommendations, setRecommendations] = useState<LifestyleRecommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadRecommendations();
  }, [reportId]);

  const loadRecommendations = async () => {
    try {
      setLoading(true);
      setError(null);
      const token = localStorage.getItem('auth_token');
      
      const response = await axios.get(
        `${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api/v1/lifestyle/recommendations/${reportId}`,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      setRecommendations(response.data.recommendations || []);
    } catch (err: any) {
      console.error('Error loading recommendations:', err);
      setError(err.response?.data?.detail || 'Failed to load recommendations');
    } finally {
      setLoading(false);
    }
  };

  const getCategoryIcon = (category: string) => {
    const icons: Record<string, any> = {
      medication: BeakerIcon,
      exercise: FireIcon,
      nutrition: HeartIcon,
      sleep: MoonIcon,
      cognitive: LightBulbIcon,
      social: UsersIcon,
      stress: SparklesIcon,
    };
    return icons[category.toLowerCase()] || SparklesIcon;
  };

  const getCategoryColor = (category: string) => {
    const colors: Record<string, { bg: string; text: string; border: string }> = {
      medication: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
      exercise: { bg: 'bg-green-50', text: 'text-green-700', border: 'border-green-200' },
      nutrition: { bg: 'bg-orange-50', text: 'text-orange-700', border: 'border-orange-200' },
      sleep: { bg: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200' },
      cognitive: { bg: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200' },
      social: { bg: 'bg-pink-50', text: 'text-pink-700', border: 'border-pink-200' },
      stress: { bg: 'bg-yellow-50', text: 'text-yellow-700', border: 'border-yellow-200' },
    };
    return (
      colors[category.toLowerCase()] || {
        bg: 'bg-gray-50',
        text: 'text-gray-700',
        border: 'border-gray-200',
      }
    );
  };

  const getPriorityBadge = (priority: string) => {
    const badges: Record<string, { bg: string; text: string }> = {
      high: { bg: 'bg-red-100', text: 'text-red-700' },
      medium: { bg: 'bg-yellow-100', text: 'text-yellow-700' },
      low: { bg: 'bg-green-100', text: 'text-green-700' },
    };
    return badges[priority] || badges.medium;
  };

  if (loading) {
    return (
      <div className="bg-white rounded-lg shadow p-8 text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-3"></div>
        <p className="text-gray-600">Loading recommendations...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6">
        <p className="text-red-700">{error}</p>
        <button
          onClick={loadRecommendations}
          className="mt-3 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
        >
          Retry
        </button>
      </div>
    );
  }

  if (recommendations.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow p-8 text-center">
        <SparklesIcon className="h-12 w-12 text-gray-400 mx-auto mb-3" />
        <p className="text-gray-600">No lifestyle recommendations available yet.</p>
        <p className="text-sm text-gray-500 mt-2">
          Recommendations will be generated based on your diagnosis report.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow p-6">
      {/* Header */}
      <div className="mb-6 pb-4 border-b border-gray-200">
        <div className="flex items-center gap-3 mb-2">
          <SparklesIcon className="h-6 w-6 text-purple-600" />
          <h3 className="text-xl font-bold text-gray-900">
            AI-Powered Lifestyle Recommendations
          </h3>
        </div>
        <p className="text-sm text-gray-600">
          Personalized recommendations generated by Google Gemini AI based on your diagnosis report
        </p>
      </div>

      {/* Recommendations Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {recommendations.map((category, index) => {
          const Icon = getCategoryIcon(category.category);
          const colors = getCategoryColor(category.category);

          return (
            <div
              key={index}
              className={`rounded-lg border-2 ${colors.border} ${colors.bg} p-5`}
            >
              {/* Category Header */}
              <div className="flex items-center gap-3 mb-4">
                <div className={`p-2 rounded-lg bg-white ${colors.border} border`}>
                  <Icon className={`h-6 w-6 ${colors.text}`} />
                </div>
                <h4 className={`text-lg font-bold ${colors.text} capitalize`}>
                  {category.category}
                </h4>
              </div>

              {/* Recommendations List */}
              <div className="space-y-3">
                {category.recommendations.map((rec, recIndex) => {
                  const priorityBadge = getPriorityBadge(rec.priority);

                  return (
                    <div
                      key={recIndex}
                      className="bg-white rounded-lg p-4 border border-gray-200"
                    >
                      <div className="flex items-start justify-between mb-2">
                        <h5 className="font-semibold text-gray-900 flex-1">{rec.title}</h5>
                        <span
                          className={`text-xs px-2 py-1 rounded-full font-medium ${priorityBadge.bg} ${priorityBadge.text} ml-2`}
                        >
                          {rec.priority.toUpperCase()}
                        </span>
                      </div>
                      <p className="text-sm text-gray-600">{rec.description}</p>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {/* Medical Disclaimer */}
      <div className="mt-6 bg-yellow-50 border border-yellow-200 rounded-lg p-4">
        <p className="text-xs text-yellow-800">
          <strong>⚠️ Important:</strong> These recommendations are AI-generated and for
          informational purposes only. Always consult with your healthcare provider before making
          any changes to your medication, exercise routine, or lifestyle. Your doctor can provide
          personalized advice based on your specific condition and medical history.
        </p>
      </div>
    </div>
  );
};

export default LifestyleRecommendationsView;
